baseURL: "https://karolinagarcia.github.io/blog"
languageCode: en-us
title: karol's blog
theme: PaperMod

params:
  env: production
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true

outputs:
    home:
        - HTML
        - RSS
        - JSON

languages:
    en:
        languageName: "English"
        weight: 1
        homeInfoParams:
          Title: "Hi! I'm Karol :)"
          Content: Here I share a little bit of my thoughts and experiences.
        socialIcons:
          - name: email
            url: 'mailto:karolinagarcia.contact@gmail.com'
          - name: github
            url: 'https://github.com/karolinagarcia'
          - name: linkedin
            url: 'https://www.linkedin.com/in/karolinagarcia/'
          - name: twitter
            url: 'https://twitter.com/karolinatgarcia'
          - name: instagram
            url: 'https://www.instagram.com/karolinatgarcia/'
        menu:
            main:
                - name: About
                  url: ../
                  weight: 1
                - name: Archive
                  url: archives/
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10

    pt:
        languageName: ":pt:"
        languageAltTitle: Portuguese
        weight: 2
        homeInfoParams:
          Title: "Oie! Eu sou a Karol :)"
          Content: Aqui eu compartilho um pouquinho das minhas experiências e reflexões.
        socialIcons:
          - name: email
            url: 'mailto:karolinagarcia.contact@gmail.com'
          - name: github
            url: 'https://github.com/karolinagarcia'
          - name: linkedin
            url: 'https://www.linkedin.com/in/karolinagarcia/'
          - name: twitter
            url: 'https://twitter.com/karolinatgarcia'
          - name: instagram
            url: 'https://www.instagram.com/karolinatgarcia/'
        menu:
            main:
                - name: About
                  url: ../
                  weight: 1
                - name: Archive
                  url: archives/
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
